services:
  - type: web
    name: gbc-connect
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://www.gbc-connect.com
      - key: FRONTEND_URL
        value: https://www.gbc-connect.com
      - key: QR_CODE_BASE_URL
        value: https://www.gbc-connect.com
      - key: BACKEND_URL
        value: https://www.gbc-connect.com
      # Firebase (frontend) configuration - direct values for production
      - key: REACT_APP_FIREBASE_API_KEY
        value: AIzaSyDe0dh5pAXKFqYqZ5-aYjd976L-vNf5uFI
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: gbc-connect-9ac56.firebaseapp.com
      - key: REACT_APP_FIREBASE_DB_URL
        value: https://gbc-connect-9ac56-default-rtdb.firebaseio.com
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: gbc-connect-9ac56
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: gbc-connect-9ac56.appspot.com
      - key: REACT_APP_FIREBASE_SENDER_ID
        value: 242600155527
      - key: REACT_APP_FIREBASE_APP_ID
        value: 1:242600155527:web:e771975170e28f96e69b22
    autoDeploy: true
    branch: main