services:
  - type: web
    name: gbc-connect
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://gbc-connect.com
      - key: FRONTEND_URL
        value: https://gbc-connect.com
      - key: QR_CODE_BASE_URL
        value: https://gbc-connect.com
      - key: BACKEND_URL
        value: https://gbc-connect.com
    autoDeploy: true
    branch: main